### ISSUE TITLE
API Documentation Page Broken

### ISSUE THREAD

**Issue by Jmoore1127** [adazzle/react-data-grid#1073]
### Which version of React JS are you using?

N/A

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details

The API Documentation link (http://adazzle.github.io/react-data-grid/documentation.html#/gettingstarted) is broken. The left nav shows but no content. Console errors in Chrome show 
```
documentation.js:3647 Uncaught TypeError: createReactClass is not a function
    at Object.1642 (documentation.js:3647)
    at __webpack_require__ (documentation.js:30)
    at Object.0 (documentation.js:70)
    at __webpack_require__ (documentation.js:30)
    at documentation.js:50
    at documentation.js:53
    at webpackUniversalModuleDefinition (documentation.js:9)
    at documentation.js:10
```

**Comment by amanmahajan7** [comment]
Thanks for reporting this bug, it was introduced in #1065. I will create a PR with a fix soon
